### ISSUE TITLE
关于 <br> 、<img> 等标签，如何处理比较好

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father-doc#18]
比如
```html
<p>
这是一张图片<br><img src="https://avatars3.githubusercontent.com/u/11746742?s=40&v=4"></p>
```
效果如下：
<p>
这是一张图片<br><img src="https://avatars3.githubusercontent.com/u/11746742?s=40&v=4"></p>

```html
<br> 和 <img> 都是没有关闭的，比如我旧的文档想切换到 `father-doc` 会涉及到较多的修改。
```

不知道，你们想怎么处理这个问题，是强制用户修改为 `<br />` 和 `<img />`，还是兼容不报错？
![image](https://user-images.githubusercontent.com/11746742/69939317-869d2500-151a-11ea-8e13-c151c104e220.png)

**Comment by PeachScript** [comment]
应该考虑做兼容处理，毕竟 HTML 5 标准也是可选的，目前用户可以使用自闭合来解决
