### ISSUE TITLE
代码里面两次单独取了yaml数据

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father-doc#20]
代码中，这个位置取到的 `config` 没在任何地方使用。
https://github.com/umijs/father-doc/blob/d79a04cbc12f48096d36ef95d07f2b47db87855a/packages/umi-plugin-father-doc/src/transformer/index.ts#L30
真正 `menu` 里面取得是 
https://github.com/umijs/father-doc/blob/d79a04cbc12f48096d36ef95d07f2b47db87855a/packages/umi-plugin-father-doc/src/routes/getFrontMatter.ts#L18

因为我想把页面的二级导航完成，不想再跑一次编译，所以，在这个 `load` 的中间过程，保留了`heading` 的数据，取完才发现，并没有把这个数据放回 `route` 中。
https://github.com/umijs/father-doc/blob/d79a04cbc12f48096d36ef95d07f2b47db87855a/packages/umi-plugin-father-doc/src/transformer/index.ts#L30
我想做的是二级导航 可以切分支 [sub-layout-data](https://github.com/umijs/father-doc/tree/sub-layout-data)
![image](https://user-images.githubusercontent.com/11746742/69959275-b3186780-1541-11ea-85b0-8313409aa19b.png)

**Comment by PeachScript** [comment]
确实是…中途改了一次实现，看来这坨逻辑出现冗余了，我尽快修复下，感谢指出。

你说的二级导航是类似 https://ant.design/docs/react/introduce-cn 右上角的 affix menu 吧？这个确实是在规划功能之中的，如果你能 PR 那是再好不过了 ❤️

**Comment by xiaohuoni** [comment]
❤️我会持续跟进这个项目，有些功能我可以帮忙实现。

**Comment by xiaohuoni** [comment]
另外麻烦看看我的其他issues和PR

**Comment by PeachScript** [comment]
那太好了，我把 alpha 阶段的一些计划放入了 #23 ，可以一起讨论看看
