### ISSUE TITLE
锚点有异常，路由使用的是hash

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father-doc#21]

**Comment by PeachScript** [comment]
这个问题有点尴尬，主要目前没接入 prerender，部署 GitHub Pages 必定要使用 hash 路由，锚点就成了 bug…

**Comment by xiaohuoni** [comment]
我记得之前有用过一个组件来实现双##定位的，要不要用类似的技术？
因为这个本质上是一个 umi 插件，也就是说非特殊情况下，umi 的配置它应该都是要支持的。
强制用户不使用hash路由好像也不是很好。

**Comment by PeachScript** [comment]
没错，这种情况肯定需要覆盖到，得对锚点部分做下改造了

**Comment by DiamondYuan** [comment]
> 这个问题有点尴尬，主要目前没接入 prerender，部署 GitHub Pages 必定要使用 hash 路由，锚点就成了 bug…

github 其实可以不用 hash 路由。
加一个 404.html 内容和 index.htm 一样就可以了。

**Comment by xiaohuoni** [comment]
嗯，这个知道。问题是页应该兼容 hash 情况下的锚点问题

**Comment by xiaohuoni** [comment]
https://github.com/umijs/father-doc/pull/39
