### ISSUE TITLE
[建议]使用yarn workspace

### ISSUE THREAD

**Issue by AimLuo** [umijs/father-doc#26]
而不是lerna bootstrap

**Comment by xiaohuoni** [comment]
为什么呢？

**Comment by AimLuo** [comment]
至少依赖包要少装很多，只有一个lock文件。我曾经用lerna管理四十个包，安装依赖都半个小时。我现在所有项目都用yarn来管理。个人觉得还不错。搭了私有npm库，下依赖超级快。

**Comment by xiaohuoni** [comment]
lerna 更多的适用于包之间有依赖关系的情况。不知道适用yarn workspace，有没有这个自动升级依赖包和自动changelog之类功能

**Comment by AimLuo** [comment]
yarn workspace是和lerna配合使用的，lerna负责版本管理，yarn workspace实现了类似lerna bootstrap以及lerna exec的功能。
✔其实如果package不多，可以不考虑。
[vue-cli](https://github.com/vuejs/vue-cli)可以参考

**Comment by AimLuo** [comment]
另外问个问题，是不是准备用father-doc来做组件文档了。docz不用了吗。
吐槽一句：docz好多bug

**Comment by Deturium** [comment]
> 另外问个问题，是不是准备用father-doc来做umijs/father的文档系统了。docz不用了吗。
> 吐槽一句：docz好多bug

是的

**Comment by PeachScript** [comment]
@AimLuo 我们用下来 Docz 确实体验比较差，father-doc 会在下一个 father 的大版本中作为 father 的 doc 核心，当前版本内不做直接替换，会添加可选参数来切换到 father-doc

**Comment by PeachScript** [comment]
关于这个问题，先不做调整吧，father-doc 很长一段时间内应该都只有两个包，当下最紧急的还是完善功能，先保证用户的体验，感谢建议❤️
