### ISSUE TITLE
webpack alias doesn't supported in embedded demo

### ISSUE THREAD

**Issue by campcc** [umijs/father-doc#30]
In local development, my project used a webpack alias,

but it doesn't work while importing module like this: 
```jsx
import Input from '@/components/Input';

export default () => <Input label="Basic Input" />;
```
Is there a better way ?

**Comment by campcc** [comment]
webpack alias doesn't supported while importing module like this: 
```jsx
import Input from '@/components/Input';

export default function () => <Input label="Basic Input" />;
```
Is there a better way ?

**Comment by PeachScript** [comment]
Was the Input component created for user?

If yes, it is recommended that import it from your project package name directly, because we should write a demo like a real user then help them use it, maybe like:

``` jsx
import Input from 'some-library'; // same as the name field in package.json

export default () => <Input />
```
