### ISSUE TITLE
autocomplete ext at external demo src attr

### ISSUE THREAD

**Issue by Deturium** [umijs/father-doc#31]
写 external demo 的时候，自动补全文件扩展名吼不吼啊

```
<code src="./webgl/triangle.tsx" />
```

这里 `.tsx` 完全可以不写，默认查找顺序可以为  `tsx`, `ts`, `jsx`, `js`，或许也可以在配置项支持用户扩展（似乎没必要）

**Comment by PeachScript** [comment]
可以，ts 和 js 暂时不做支持了，father-doc 现在会对默认导出 `createElement`，不返回 React Component 无法工作
