### ISSUE TITLE
建议增加prettierrc

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father-doc#33]
我发现我们本地的 prettier 规则不同，我保存的时候，会格式化一些代码，在我提交代码的时候，我还需要很小心的不要提交这些无用变更
我尝试这添加配置，但是ts里面的 `?.` 不知道该怎么配置
![image](https://user-images.githubusercontent.com/11746742/70439222-73fe8f00-1aca-11ea-8ce9-913f942020b4.png)

**Comment by PeachScript** [comment]
同感…主要我没用 prettier 但你用了，这样就很容易发生冲突

**Comment by PeachScript** [comment]
配置我们都研究下，临时解决方案要么先禁用掉 prettier

**Comment by xiaohuoni** [comment]
手动格式化嘛？代码洁癖狂魔，果然不是虚传。

**Comment by AimLuo** [comment]
我现在项目格式化全部采用umi-fabric，贼爽。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/father-doc/pull/35
