### ISSUE TITLE
Parse & process YAML config from .md file

### ISSUE THREAD

**Issue by PeachScript** [umijs/father-doc#4]

**Comment by xiaohuoni** [comment]
YAML config https://github.com/xiaohuoni/github-theme-docs/blob/2c14a15db986834d3c3ab7176c2e6e4cce620faa/config/plugin.js#L103

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/js-yaml

**Comment by PeachScript** [comment]
第一个链接失效了
