### ISSUE TITLE
Multi-language mode design RFC

### ISSUE THREAD

**Issue by PeachScript** [umijs/father-doc#45]
目前设想下来多语言的支持仍然是『约定式』的，与各位讨论下具体实现规则是否合理：

## 多语言文件检测

如果 markdown 文件的文件名组成是 `filename.lang.md`，则该文件会被检测为 `filename.md` 在 `lang` 下的渲染组件，这个 `lang` 原则上不限制格式，也就是说我们写 `en` 或者 `en-US` 都会被检测到。

## 多语言的路由生成

一旦触发上述检测条件，`lang` 会作为路由的前缀被生成一个新路由。例如 `index.md` 的路由如果是 `/hello`，那么 `index.en.md` 的路由就会是 `/en/hello`。

## 多语言的切换

设想是默认主题新增一个切换语言的地方，形式应该是 Select Menu，但具体样式还没想好。

## 多语言的默认语言约定

只要没有带 `lang` 部分的 markdown，就会被当做默认语言渲染。例如，如果我的文档站默认英文，那么我的 markdown 文件应该是 `index.md` 和 `index.zh-CN.md`；如果我的文档站默认中文，那么我的 markdown 文件应该是 `index.md` 和 `index.en-US.md`。

以上规则的设计原则只有一个，**把功能尽可能约定化**，也就是说理想情况下初期不会有任何关于 locales 的配置出现。

**Comment by brickspert** [comment]
demo 的 title, description 如何国际化？ 
目前 hooks 的做法是：
1. demo 本身只要英文的，没有中文的。
2. demo 的 title/description 有中英文区别。

**Comment by tli4** [comment]
> 只要没有带 lang 部分的 markdown，就会被当做默认语言渲染。例如，如果我的文档站默认英文，那么我的 markdown 文件应该是 index.md 和 index.zh-CN.md；如果我的文档站默认中文，那么我的 markdown 文件应该是 index.md 和 index.en-US.md

这样 Select 好像并不知道默认语言是什么。
感觉可以是约定 + 可配置式的，比如在 .umirc 里配置一下每个语言的别名：

```js
languages: {
  default: '中文',
  'en-US': 'English',
  'zh-TW': '繁體中文'
}
```

这样 Select 的下拉框里可以就显示: 中文、English、繁體中文

**Comment by PeachScript** [comment]
> demo 的 title, description 如何国际化
@brickspert title 和 desc 可以考虑增加字段，比如 `title.zh-CN`

**Comment by PeachScript** [comment]
> 这样 Select 好像并不知道默认语言是什么。
@tli4 好角度…确实有这个尴尬的问题存在，看来不可避免要提供配置了🤦‍♂️

**Comment by xiaohuoni** [comment]
> 这个 lang 原则上不限制格式，也就是说我们写 en 或者 en-US 都会被检测到。

原则上来说不限制格式并没有多余的好处，统一约定好 lang 就好。如 `*.zh-CN` 为中文

**Comment by PeachScript** [comment]
> 原则上来说不限制格式并没有多余的好处，统一约定好 lang 就好。如 *.zh-CN 为中文

@xiaohuoni 有些用户可能需要在路由上隐藏掉地区，比如 `zh-CN` 在路由上仅显示为 `zh`，要支持这个的话就得扩展新配置了

**Comment by chenshuai2144** [comment]
/en/filename -> filename-cn 比较好一点。

**Comment by PeachScript** [comment]
@chenjsh36 en 永远在最顶层，一般的国际化站点都是这么搞的吧

**Comment by PeachScript** [comment]
根据此前的讨论情况提了个 PR，各位一起 review 下：https://github.com/umijs/father-doc/pull/58
