### ISSUE TITLE
🐛[BUG] father-doc生成的文件部署到github page会报umi.css和umi.js 404

### ISSUE THREAD

**Issue by chj-damon** [umijs/father-doc#48]
### 🐛 bug 描述

使用`father-doc build`命令会在项目根目录生成一个`dist`文件夹，包含三个文件：
`index.html`, `umi.css`和`umi.js`。
其中，`index.html`里面的内容是：
```html
<!DOCTYPE html><html><head><link rel="stylesheet" href="/umi.css"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"><title>雷数前端</title><script>window.routerBase = "/";</script></head><body><div id="root"></div><script src="/umi.js"></script></body></html>
```
可以看到，引用css和js的路径是/而不是./，这样会导致在把代码推到github pages之后，无法正常加载css和js文件。
### © 版本信息

- father-doc 版本: 1.0.0-alpha.7
- node 版本: v10.16.0
- 浏览器环境: 79.0.3945.79
- 开发环境: macOS Mojave 10.14.6

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/4902684/71172602-9bf4ac00-229b-11ea-9acf-94a5f94f05c6.png)
![image](https://user-images.githubusercontent.com/4902684/71172673-ce9ea480-229b-11ea-9c8e-5e51335d2b57.png)
![image](https://user-images.githubusercontent.com/4902684/71172618-ab73f500-229b-11ea-97e1-0532c8328653.png)

**Comment by chenshuai2144** [comment]
配置publicPath 和 base 即可。
https://umijs.org/config/#publicpath

**Comment by chj-damon** [comment]
@chenshuai2144 奇怪，为什么你这里不配是可以的呢？
https://github.com/ant-design/pro-table/blob/gh-pages/index.html

**Comment by chenshuai2144** [comment]
我挂了域名。变成  / 了

**Comment by kokiy** [comment]
@chenshuai2144  配置了 base 和 publicPath 是可以访问了.但是如果加了 dumi-theme-mobile ,github pages 访问不到呢

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/106103440-e5d8e280-617b-11eb-895f-2cbbdb96ca9a.png)


直接打开 exportStatic
