### ISSUE TITLE
🐛[BUG]group.order 不起作用

### ISSUE THREAD

**Issue by chj-damon** [umijs/father-doc#57]
### 🐛 bug 描述

按照[https://umijs.github.io/father-doc/#/config/frontmatter](https://umijs.github.io/father-doc/#/config/frontmatter)里面关于`group.order`的说明，值越大的越排在前面，但是我配置发现不起作用。

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/4902684/71575147-cb6ea880-2b26-11ea-8110-5d3fc8b561f5.png)
![image](https://user-images.githubusercontent.com/4902684/71575153-cf9ac600-2b26-11ea-9cb7-04fd44e89f10.png)

### 🏞 期望结果
按照上图的配置，期望的顺序应该是Web组件库、APP组件库、博文，但是实际上的顺序是APP组件库、博文、Web组件库

### © 版本信息

- father-doc 版本: 1.0.0-alpha.7
- node 版本: v10.16.0
- 浏览器环境: 79.0.3945.79
- 开发环境: macOS Mojave 10.14.6

**Comment by PeachScript** [comment]
感谢反馈 ❤️ 

问题在 v1.0.0-alpha.12 中已修复，issue 关闭
