### ISSUE TITLE
🐛[BUG]npm i father-doc@next -D  报错

### ISSUE THREAD

**Issue by fanhualei** [umijs/father-doc#60]
### 🐛 bug 描述

npm i father-doc@next -D  报错。

把@next去掉就好了。

![TIM截图20200111204925](https://user-images.githubusercontent.com/34436863/72204513-e260b380-34b3-11ea-96c6-f1dbae5bad73.png)

### © 版本信息

- father-doc 版本: [e.g. 1.0.0]
- node 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by PeachScript** [comment]
是文档的 bug，已修复，感谢反馈
