### ISSUE TITLE
👑 [需求] 怎么在文档中使用代理

### ISSUE THREAD

**Issue by OxPatient** [umijs/father-doc#61]
### 🥰 需求描述

在文档中，组件需要访问API获取数据进行渲染，请问如何在father-doc中设置代码

**Comment by xiaohuoni** [comment]
理论上应该可以通过proxy配置请求。

**Comment by OxPatient** [comment]
使用UMI配置可行

**Comment by amyhuangxbd** [comment]
> 使用UMI配置可行

我在.umirc.ts 中配置proxy 还是没有成功
`import { defineConfig } from 'dumi';

const os = require("os");
const ifaces = os.networkInterfaces();

export const getHost = () => {
  let host = '127.0.0.1';
  let hasFound = false

  for (const dev in ifaces) {
      ifaces[dev].forEach(function(details) {
          if(hasFound) return
          if (details.family === 'IPv4' && details.address.indexOf('192.168') >= 0) {
              host = details.address;
              hasFound=true
          }
      });
  }

  return host;
};

export default defineConfig({
  title: 'trialos-ui-common',
  outputPath: 'docs-dist',
  proxy: {
    '/api': {
      'target': 'http://xxx.test.com',
      'changeOrigin': true,
      'pathRewrite': { '^/$': '', },
      cookieDomainRewrite: getHost(),
    },
  },
  extraBabelPlugins: [
    ['babel-plugin-import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: true,
    }],
  ],
});
`
你是怎么配置的？

**Comment by tancyan** [comment]
请问这个问题为什么会关闭呀？最终怎么解决么？
proxy仅在dev生效呀，线上部署的doc怎么能用proxy呢？
