### ISSUE TITLE
👑 [需求]md中写tsx，没有检查和提示

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/father-doc#70]
在md中写tsx没有了TS静态类型检查，也没有了TS的代码提示功能，这个有办法改进么

**Comment by PeachScript** [comment]
应该只能开发一个 vscode 插件解决，目前没有相关计划且可预见维护成本会很高
对于这种场景，请使用外部 demo 引入 tsx 文件，这也是 father-doc 支持外部 demo 的原因之一
