### ISSUE TITLE
🐛[BUG] demo desc 换行后识别错误

### ISSUE THREAD

**Issue by brickspert** [umijs/father-doc#73]
### 🐛 bug 描述

demo 中的 desc 不能换行，换行后识别错误。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/12526493/73513471-8e991880-4428-11ea-98f3-1af1052af239.png)

**Comment by PeachScript** [comment]
yaml 语法需要加标识符才能换行：https://www.ruanyifeng.com/blog/2016/07/yaml.html
只要 `desc` 支持写 markdown，该问题就不存在了，由 #75 跟进
