### ISSUE TITLE
👑 [需求] demo desc 支持 markdown 语法

### ISSUE THREAD

**Issue by brickspert** [umijs/father-doc#75]
### 🥰 需求描述

希望 demo desc 支持 markdown 语法

![image](https://user-images.githubusercontent.com/12526493/73515409-2cdcac80-4430-11ea-9250-25f25cb51310.png)

**Comment by brickspert** [comment]
支持复杂的 desc

![image](https://user-images.githubusercontent.com/12526493/73523005-df1e6f00-4444-11ea-8b8a-37a0ac006fa4.png)

**Comment by HaiYoungs** [comment]
请问怎么配置 title 和 desc 的字号，好像不支持配置
